// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module DataMoverUnit_s2mm_32bits_dataflow_in_loop_S2M (
        STR_video_in_TDATA,
        STR_video_in_TKEEP,
        STR_video_in_TSTRB,
        STR_video_in_TUSER,
        STR_video_in_TLAST,
        image_w,
        invert_X,
        m_axi_MM_video_out_AWVALID,
        m_axi_MM_video_out_AWREADY,
        m_axi_MM_video_out_AWADDR,
        m_axi_MM_video_out_AWID,
        m_axi_MM_video_out_AWLEN,
        m_axi_MM_video_out_AWSIZE,
        m_axi_MM_video_out_AWBURST,
        m_axi_MM_video_out_AWLOCK,
        m_axi_MM_video_out_AWCACHE,
        m_axi_MM_video_out_AWPROT,
        m_axi_MM_video_out_AWQOS,
        m_axi_MM_video_out_AWREGION,
        m_axi_MM_video_out_AWUSER,
        m_axi_MM_video_out_WVALID,
        m_axi_MM_video_out_WREADY,
        m_axi_MM_video_out_WDATA,
        m_axi_MM_video_out_WSTRB,
        m_axi_MM_video_out_WLAST,
        m_axi_MM_video_out_WID,
        m_axi_MM_video_out_WUSER,
        m_axi_MM_video_out_ARVALID,
        m_axi_MM_video_out_ARREADY,
        m_axi_MM_video_out_ARADDR,
        m_axi_MM_video_out_ARID,
        m_axi_MM_video_out_ARLEN,
        m_axi_MM_video_out_ARSIZE,
        m_axi_MM_video_out_ARBURST,
        m_axi_MM_video_out_ARLOCK,
        m_axi_MM_video_out_ARCACHE,
        m_axi_MM_video_out_ARPROT,
        m_axi_MM_video_out_ARQOS,
        m_axi_MM_video_out_ARREGION,
        m_axi_MM_video_out_ARUSER,
        m_axi_MM_video_out_RVALID,
        m_axi_MM_video_out_RREADY,
        m_axi_MM_video_out_RDATA,
        m_axi_MM_video_out_RLAST,
        m_axi_MM_video_out_RID,
        m_axi_MM_video_out_RUSER,
        m_axi_MM_video_out_RRESP,
        m_axi_MM_video_out_BVALID,
        m_axi_MM_video_out_BREADY,
        m_axi_MM_video_out_BRESP,
        m_axi_MM_video_out_BID,
        m_axi_MM_video_out_BUSER,
        ddr_buffer_out,
        DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0,
        image_h,
        invert_Y,
        ap_clk,
        ap_rst,
        image_w_ap_vld,
        invert_X_ap_vld,
        ddr_buffer_out_ap_vld,
        DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_ap_vld,
        image_h_ap_vld,
        invert_Y_ap_vld,
        ap_start,
        STR_video_in_TVALID,
        STR_video_in_TREADY,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [7:0] STR_video_in_TDATA;
input  [0:0] STR_video_in_TKEEP;
input  [0:0] STR_video_in_TSTRB;
input  [0:0] STR_video_in_TUSER;
input  [0:0] STR_video_in_TLAST;
input  [31:0] image_w;
input  [0:0] invert_X;
output   m_axi_MM_video_out_AWVALID;
input   m_axi_MM_video_out_AWREADY;
output  [31:0] m_axi_MM_video_out_AWADDR;
output  [0:0] m_axi_MM_video_out_AWID;
output  [31:0] m_axi_MM_video_out_AWLEN;
output  [2:0] m_axi_MM_video_out_AWSIZE;
output  [1:0] m_axi_MM_video_out_AWBURST;
output  [1:0] m_axi_MM_video_out_AWLOCK;
output  [3:0] m_axi_MM_video_out_AWCACHE;
output  [2:0] m_axi_MM_video_out_AWPROT;
output  [3:0] m_axi_MM_video_out_AWQOS;
output  [3:0] m_axi_MM_video_out_AWREGION;
output  [0:0] m_axi_MM_video_out_AWUSER;
output   m_axi_MM_video_out_WVALID;
input   m_axi_MM_video_out_WREADY;
output  [31:0] m_axi_MM_video_out_WDATA;
output  [3:0] m_axi_MM_video_out_WSTRB;
output   m_axi_MM_video_out_WLAST;
output  [0:0] m_axi_MM_video_out_WID;
output  [0:0] m_axi_MM_video_out_WUSER;
output   m_axi_MM_video_out_ARVALID;
input   m_axi_MM_video_out_ARREADY;
output  [31:0] m_axi_MM_video_out_ARADDR;
output  [0:0] m_axi_MM_video_out_ARID;
output  [31:0] m_axi_MM_video_out_ARLEN;
output  [2:0] m_axi_MM_video_out_ARSIZE;
output  [1:0] m_axi_MM_video_out_ARBURST;
output  [1:0] m_axi_MM_video_out_ARLOCK;
output  [3:0] m_axi_MM_video_out_ARCACHE;
output  [2:0] m_axi_MM_video_out_ARPROT;
output  [3:0] m_axi_MM_video_out_ARQOS;
output  [3:0] m_axi_MM_video_out_ARREGION;
output  [0:0] m_axi_MM_video_out_ARUSER;
input   m_axi_MM_video_out_RVALID;
output   m_axi_MM_video_out_RREADY;
input  [31:0] m_axi_MM_video_out_RDATA;
input   m_axi_MM_video_out_RLAST;
input  [0:0] m_axi_MM_video_out_RID;
input  [0:0] m_axi_MM_video_out_RUSER;
input  [1:0] m_axi_MM_video_out_RRESP;
input   m_axi_MM_video_out_BVALID;
output   m_axi_MM_video_out_BREADY;
input  [1:0] m_axi_MM_video_out_BRESP;
input  [0:0] m_axi_MM_video_out_BID;
input  [0:0] m_axi_MM_video_out_BUSER;
input  [31:0] ddr_buffer_out;
input  [30:0] DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0;
input  [20:0] image_h;
input  [0:0] invert_Y;
input   ap_clk;
input   ap_rst;
input   image_w_ap_vld;
input   invert_X_ap_vld;
input   ddr_buffer_out_ap_vld;
input   DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_ap_vld;
input   image_h_ap_vld;
input   invert_Y_ap_vld;
input   ap_start;
input   STR_video_in_TVALID;
output   STR_video_in_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    dataflow_in_loop_S2M_entry4_U0_ap_start;
wire    dataflow_in_loop_S2M_entry4_U0_ap_done;
wire    dataflow_in_loop_S2M_entry4_U0_ap_continue;
wire    dataflow_in_loop_S2M_entry4_U0_ap_idle;
wire    dataflow_in_loop_S2M_entry4_U0_ap_ready;
wire    dataflow_in_loop_S2M_entry4_U0_start_out;
wire    dataflow_in_loop_S2M_entry4_U0_start_write;
wire   [31:0] dataflow_in_loop_S2M_entry4_U0_image_w_out_din;
wire    dataflow_in_loop_S2M_entry4_U0_image_w_out_write;
wire   [0:0] dataflow_in_loop_S2M_entry4_U0_invert_X_out_din;
wire    dataflow_in_loop_S2M_entry4_U0_invert_X_out_write;
wire   [31:0] dataflow_in_loop_S2M_entry4_U0_ddr_buffer_out_out_din;
wire    dataflow_in_loop_S2M_entry4_U0_ddr_buffer_out_out_write;
wire   [30:0] dataflow_in_loop_S2M_entry4_U0_DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_din;
wire    dataflow_in_loop_S2M_entry4_U0_DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_write;
wire   [20:0] dataflow_in_loop_S2M_entry4_U0_image_h_out_din;
wire    dataflow_in_loop_S2M_entry4_U0_image_h_out_write;
wire   [0:0] dataflow_in_loop_S2M_entry4_U0_invert_Y_out_din;
wire    dataflow_in_loop_S2M_entry4_U0_invert_Y_out_write;
wire    FillLocalBuffer7_U0_ap_start;
wire    FillLocalBuffer7_U0_ap_done;
wire    FillLocalBuffer7_U0_ap_continue;
wire    FillLocalBuffer7_U0_ap_idle;
wire    FillLocalBuffer7_U0_ap_ready;
wire    FillLocalBuffer7_U0_STR_video_in_TREADY;
wire    FillLocalBuffer7_U0_image_w_read;
wire    FillLocalBuffer7_U0_invert_X_read;
wire   [10:0] FillLocalBuffer7_U0_stream_elt_dma_buffer_V_address0;
wire    FillLocalBuffer7_U0_stream_elt_dma_buffer_V_ce0;
wire    FillLocalBuffer7_U0_stream_elt_dma_buffer_V_we0;
wire   [7:0] FillLocalBuffer7_U0_stream_elt_dma_buffer_V_d0;
wire    FillLocalBuffer7_U0_ddr_buffer_out_read;
wire    FillLocalBuffer7_U0_DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_read;
wire    FillLocalBuffer7_U0_image_h_read;
wire    FillLocalBuffer7_U0_invert_Y_read;
wire   [31:0] FillLocalBuffer7_U0_image_w_c_din;
wire    FillLocalBuffer7_U0_image_w_c_write;
wire   [31:0] FillLocalBuffer7_U0_ddr_buffer_out_c_din;
wire    FillLocalBuffer7_U0_ddr_buffer_out_c_write;
wire   [20:0] FillLocalBuffer7_U0_DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_c_din;
wire    FillLocalBuffer7_U0_DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_c_write;
wire   [20:0] FillLocalBuffer7_U0_image_h_c_din;
wire    FillLocalBuffer7_U0_image_h_c_write;
wire   [0:0] FillLocalBuffer7_U0_invert_Y_c_din;
wire    FillLocalBuffer7_U0_invert_Y_c_write;
wire    ap_channel_done_stream_elt_dma_buffer_V;
wire    FillLocalBuffer7_U0_stream_elt_dma_buffer_V_full_n;
wire    S2M_FormatLocalBuffer_U0_ap_start;
wire    S2M_FormatLocalBuffer_U0_ap_done;
wire    S2M_FormatLocalBuffer_U0_ap_continue;
wire    S2M_FormatLocalBuffer_U0_ap_idle;
wire    S2M_FormatLocalBuffer_U0_ap_ready;
wire   [10:0] S2M_FormatLocalBuffer_U0_stream_elt_dma_buffer_V_address0;
wire    S2M_FormatLocalBuffer_U0_stream_elt_dma_buffer_V_ce0;
wire   [10:0] S2M_FormatLocalBuffer_U0_stream_elt_dma_buffer_V_address1;
wire    S2M_FormatLocalBuffer_U0_stream_elt_dma_buffer_V_ce1;
wire   [8:0] S2M_FormatLocalBuffer_U0_axi_elt_dma_buffer_V_address0;
wire    S2M_FormatLocalBuffer_U0_axi_elt_dma_buffer_V_ce0;
wire    S2M_FormatLocalBuffer_U0_axi_elt_dma_buffer_V_we0;
wire   [31:0] S2M_FormatLocalBuffer_U0_axi_elt_dma_buffer_V_d0;
wire    ap_channel_done_axi_elt_dma_buffer_V;
wire    S2M_FormatLocalBuffer_U0_axi_elt_dma_buffer_V_full_n;
wire    DMAWriteMM_U0_ap_start;
wire    DMAWriteMM_U0_ap_done;
wire    DMAWriteMM_U0_ap_continue;
wire    DMAWriteMM_U0_ap_idle;
wire    DMAWriteMM_U0_ap_ready;
wire    DMAWriteMM_U0_m_axi_MM_video_out_AWVALID;
wire   [31:0] DMAWriteMM_U0_m_axi_MM_video_out_AWADDR;
wire   [0:0] DMAWriteMM_U0_m_axi_MM_video_out_AWID;
wire   [31:0] DMAWriteMM_U0_m_axi_MM_video_out_AWLEN;
wire   [2:0] DMAWriteMM_U0_m_axi_MM_video_out_AWSIZE;
wire   [1:0] DMAWriteMM_U0_m_axi_MM_video_out_AWBURST;
wire   [1:0] DMAWriteMM_U0_m_axi_MM_video_out_AWLOCK;
wire   [3:0] DMAWriteMM_U0_m_axi_MM_video_out_AWCACHE;
wire   [2:0] DMAWriteMM_U0_m_axi_MM_video_out_AWPROT;
wire   [3:0] DMAWriteMM_U0_m_axi_MM_video_out_AWQOS;
wire   [3:0] DMAWriteMM_U0_m_axi_MM_video_out_AWREGION;
wire   [0:0] DMAWriteMM_U0_m_axi_MM_video_out_AWUSER;
wire    DMAWriteMM_U0_m_axi_MM_video_out_WVALID;
wire   [31:0] DMAWriteMM_U0_m_axi_MM_video_out_WDATA;
wire   [3:0] DMAWriteMM_U0_m_axi_MM_video_out_WSTRB;
wire    DMAWriteMM_U0_m_axi_MM_video_out_WLAST;
wire   [0:0] DMAWriteMM_U0_m_axi_MM_video_out_WID;
wire   [0:0] DMAWriteMM_U0_m_axi_MM_video_out_WUSER;
wire    DMAWriteMM_U0_m_axi_MM_video_out_ARVALID;
wire   [31:0] DMAWriteMM_U0_m_axi_MM_video_out_ARADDR;
wire   [0:0] DMAWriteMM_U0_m_axi_MM_video_out_ARID;
wire   [31:0] DMAWriteMM_U0_m_axi_MM_video_out_ARLEN;
wire   [2:0] DMAWriteMM_U0_m_axi_MM_video_out_ARSIZE;
wire   [1:0] DMAWriteMM_U0_m_axi_MM_video_out_ARBURST;
wire   [1:0] DMAWriteMM_U0_m_axi_MM_video_out_ARLOCK;
wire   [3:0] DMAWriteMM_U0_m_axi_MM_video_out_ARCACHE;
wire   [2:0] DMAWriteMM_U0_m_axi_MM_video_out_ARPROT;
wire   [3:0] DMAWriteMM_U0_m_axi_MM_video_out_ARQOS;
wire   [3:0] DMAWriteMM_U0_m_axi_MM_video_out_ARREGION;
wire   [0:0] DMAWriteMM_U0_m_axi_MM_video_out_ARUSER;
wire    DMAWriteMM_U0_m_axi_MM_video_out_RREADY;
wire    DMAWriteMM_U0_m_axi_MM_video_out_BREADY;
wire    DMAWriteMM_U0_ddr_buffer_out_read;
wire    DMAWriteMM_U0_DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_read;
wire    DMAWriteMM_U0_image_h_read;
wire    DMAWriteMM_U0_image_w_read;
wire    DMAWriteMM_U0_invert_Y_read;
wire   [8:0] DMAWriteMM_U0_axi_elt_dma_buffer_V_address0;
wire    DMAWriteMM_U0_axi_elt_dma_buffer_V_ce0;
wire    ap_sync_continue;
wire   [7:0] stream_elt_dma_buffer_V_i_q0;
wire   [7:0] stream_elt_dma_buffer_V_i_q1;
wire   [7:0] stream_elt_dma_buffer_V_t_q0;
wire   [7:0] stream_elt_dma_buffer_V_t_q1;
wire    stream_elt_dma_buffer_V_i_full_n;
wire    stream_elt_dma_buffer_V_t_empty_n;
wire   [7:0] stream_elt_dma_buffer_V_t_d1;
wire    stream_elt_dma_buffer_V_t_we1;
wire   [31:0] axi_elt_dma_buffer_V_i_q0;
wire   [31:0] axi_elt_dma_buffer_V_t_q0;
wire    axi_elt_dma_buffer_V_i_full_n;
wire    axi_elt_dma_buffer_V_t_empty_n;
wire    image_w_c1_full_n;
wire   [31:0] image_w_c1_dout;
wire    image_w_c1_empty_n;
wire    invert_X_c_full_n;
wire   [0:0] invert_X_c_dout;
wire    invert_X_c_empty_n;
wire    ddr_buffer_out_c2_full_n;
wire   [31:0] ddr_buffer_out_c2_dout;
wire    ddr_buffer_out_c2_empty_n;
wire    DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_c3_full_n;
wire   [30:0] DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_c3_dout;
wire    DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_c3_empty_n;
wire    image_h_c4_full_n;
wire   [20:0] image_h_c4_dout;
wire    image_h_c4_empty_n;
wire    invert_Y_c5_full_n;
wire   [0:0] invert_Y_c5_dout;
wire    invert_Y_c5_empty_n;
wire    image_w_c_full_n;
wire   [31:0] image_w_c_dout;
wire    image_w_c_empty_n;
wire    ddr_buffer_out_c_full_n;
wire   [31:0] ddr_buffer_out_c_dout;
wire    ddr_buffer_out_c_empty_n;
wire    DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_c_full_n;
wire   [20:0] DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_c_dout;
wire    DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_c_empty_n;
wire    image_h_c_full_n;
wire   [20:0] image_h_c_dout;
wire    image_h_c_empty_n;
wire    invert_Y_c_full_n;
wire   [0:0] invert_Y_c_dout;
wire    invert_Y_c_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_FillLocalBuffer7_U0_din;
wire    start_for_FillLocalBuffer7_U0_full_n;
wire   [0:0] start_for_FillLocalBuffer7_U0_dout;
wire    start_for_FillLocalBuffer7_U0_empty_n;
wire    FillLocalBuffer7_U0_start_full_n;
wire    FillLocalBuffer7_U0_start_write;
wire    S2M_FormatLocalBuffer_U0_start_full_n;
wire    S2M_FormatLocalBuffer_U0_start_write;
wire    DMAWriteMM_U0_start_full_n;
wire    DMAWriteMM_U0_start_write;

DataMoverUnit_s2mm_32bits_dataflow_in_loop_S2M_entry4 dataflow_in_loop_S2M_entry4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(dataflow_in_loop_S2M_entry4_U0_ap_start),
    .start_full_n(start_for_FillLocalBuffer7_U0_full_n),
    .ap_done(dataflow_in_loop_S2M_entry4_U0_ap_done),
    .ap_continue(dataflow_in_loop_S2M_entry4_U0_ap_continue),
    .ap_idle(dataflow_in_loop_S2M_entry4_U0_ap_idle),
    .ap_ready(dataflow_in_loop_S2M_entry4_U0_ap_ready),
    .start_out(dataflow_in_loop_S2M_entry4_U0_start_out),
    .start_write(dataflow_in_loop_S2M_entry4_U0_start_write),
    .image_w(image_w),
    .invert_X(invert_X),
    .ddr_buffer_out(ddr_buffer_out),
    .DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0(DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0),
    .image_h(image_h),
    .invert_Y(invert_Y),
    .image_w_out_din(dataflow_in_loop_S2M_entry4_U0_image_w_out_din),
    .image_w_out_full_n(image_w_c1_full_n),
    .image_w_out_write(dataflow_in_loop_S2M_entry4_U0_image_w_out_write),
    .invert_X_out_din(dataflow_in_loop_S2M_entry4_U0_invert_X_out_din),
    .invert_X_out_full_n(invert_X_c_full_n),
    .invert_X_out_write(dataflow_in_loop_S2M_entry4_U0_invert_X_out_write),
    .ddr_buffer_out_out_din(dataflow_in_loop_S2M_entry4_U0_ddr_buffer_out_out_din),
    .ddr_buffer_out_out_full_n(ddr_buffer_out_c2_full_n),
    .ddr_buffer_out_out_write(dataflow_in_loop_S2M_entry4_U0_ddr_buffer_out_out_write),
    .DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_din(dataflow_in_loop_S2M_entry4_U0_DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_din),
    .DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_full_n(DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_c3_full_n),
    .DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_write(dataflow_in_loop_S2M_entry4_U0_DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_write),
    .image_h_out_din(dataflow_in_loop_S2M_entry4_U0_image_h_out_din),
    .image_h_out_full_n(image_h_c4_full_n),
    .image_h_out_write(dataflow_in_loop_S2M_entry4_U0_image_h_out_write),
    .invert_Y_out_din(dataflow_in_loop_S2M_entry4_U0_invert_Y_out_din),
    .invert_Y_out_full_n(invert_Y_c5_full_n),
    .invert_Y_out_write(dataflow_in_loop_S2M_entry4_U0_invert_Y_out_write)
);

DataMoverUnit_s2mm_32bits_FillLocalBuffer7 FillLocalBuffer7_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(FillLocalBuffer7_U0_ap_start),
    .ap_done(FillLocalBuffer7_U0_ap_done),
    .ap_continue(FillLocalBuffer7_U0_ap_continue),
    .ap_idle(FillLocalBuffer7_U0_ap_idle),
    .ap_ready(FillLocalBuffer7_U0_ap_ready),
    .STR_video_in_TDATA(STR_video_in_TDATA),
    .STR_video_in_TVALID(STR_video_in_TVALID),
    .STR_video_in_TREADY(FillLocalBuffer7_U0_STR_video_in_TREADY),
    .STR_video_in_TKEEP(STR_video_in_TKEEP),
    .STR_video_in_TSTRB(STR_video_in_TSTRB),
    .STR_video_in_TUSER(STR_video_in_TUSER),
    .STR_video_in_TLAST(STR_video_in_TLAST),
    .image_w_dout(image_w_c1_dout),
    .image_w_empty_n(image_w_c1_empty_n),
    .image_w_read(FillLocalBuffer7_U0_image_w_read),
    .invert_X_dout(invert_X_c_dout),
    .invert_X_empty_n(invert_X_c_empty_n),
    .invert_X_read(FillLocalBuffer7_U0_invert_X_read),
    .stream_elt_dma_buffer_V_address0(FillLocalBuffer7_U0_stream_elt_dma_buffer_V_address0),
    .stream_elt_dma_buffer_V_ce0(FillLocalBuffer7_U0_stream_elt_dma_buffer_V_ce0),
    .stream_elt_dma_buffer_V_we0(FillLocalBuffer7_U0_stream_elt_dma_buffer_V_we0),
    .stream_elt_dma_buffer_V_d0(FillLocalBuffer7_U0_stream_elt_dma_buffer_V_d0),
    .ddr_buffer_out_dout(ddr_buffer_out_c2_dout),
    .ddr_buffer_out_empty_n(ddr_buffer_out_c2_empty_n),
    .ddr_buffer_out_read(FillLocalBuffer7_U0_ddr_buffer_out_read),
    .DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_dout(DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_c3_dout),
    .DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_empty_n(DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_c3_empty_n),
    .DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_read(FillLocalBuffer7_U0_DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_read),
    .image_h_dout(image_h_c4_dout),
    .image_h_empty_n(image_h_c4_empty_n),
    .image_h_read(FillLocalBuffer7_U0_image_h_read),
    .invert_Y_dout(invert_Y_c5_dout),
    .invert_Y_empty_n(invert_Y_c5_empty_n),
    .invert_Y_read(FillLocalBuffer7_U0_invert_Y_read),
    .image_w_c_din(FillLocalBuffer7_U0_image_w_c_din),
    .image_w_c_full_n(image_w_c_full_n),
    .image_w_c_write(FillLocalBuffer7_U0_image_w_c_write),
    .ddr_buffer_out_c_din(FillLocalBuffer7_U0_ddr_buffer_out_c_din),
    .ddr_buffer_out_c_full_n(ddr_buffer_out_c_full_n),
    .ddr_buffer_out_c_write(FillLocalBuffer7_U0_ddr_buffer_out_c_write),
    .DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_c_din(FillLocalBuffer7_U0_DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_c_din),
    .DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_c_full_n(DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_c_full_n),
    .DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_c_write(FillLocalBuffer7_U0_DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_c_write),
    .image_h_c_din(FillLocalBuffer7_U0_image_h_c_din),
    .image_h_c_full_n(image_h_c_full_n),
    .image_h_c_write(FillLocalBuffer7_U0_image_h_c_write),
    .invert_Y_c_din(FillLocalBuffer7_U0_invert_Y_c_din),
    .invert_Y_c_full_n(invert_Y_c_full_n),
    .invert_Y_c_write(FillLocalBuffer7_U0_invert_Y_c_write)
);

DataMoverUnit_s2mm_32bits_S2M_FormatLocalBuffer S2M_FormatLocalBuffer_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(S2M_FormatLocalBuffer_U0_ap_start),
    .ap_done(S2M_FormatLocalBuffer_U0_ap_done),
    .ap_continue(S2M_FormatLocalBuffer_U0_ap_continue),
    .ap_idle(S2M_FormatLocalBuffer_U0_ap_idle),
    .ap_ready(S2M_FormatLocalBuffer_U0_ap_ready),
    .stream_elt_dma_buffer_V_address0(S2M_FormatLocalBuffer_U0_stream_elt_dma_buffer_V_address0),
    .stream_elt_dma_buffer_V_ce0(S2M_FormatLocalBuffer_U0_stream_elt_dma_buffer_V_ce0),
    .stream_elt_dma_buffer_V_q0(stream_elt_dma_buffer_V_t_q0),
    .stream_elt_dma_buffer_V_address1(S2M_FormatLocalBuffer_U0_stream_elt_dma_buffer_V_address1),
    .stream_elt_dma_buffer_V_ce1(S2M_FormatLocalBuffer_U0_stream_elt_dma_buffer_V_ce1),
    .stream_elt_dma_buffer_V_q1(stream_elt_dma_buffer_V_t_q1),
    .axi_elt_dma_buffer_V_address0(S2M_FormatLocalBuffer_U0_axi_elt_dma_buffer_V_address0),
    .axi_elt_dma_buffer_V_ce0(S2M_FormatLocalBuffer_U0_axi_elt_dma_buffer_V_ce0),
    .axi_elt_dma_buffer_V_we0(S2M_FormatLocalBuffer_U0_axi_elt_dma_buffer_V_we0),
    .axi_elt_dma_buffer_V_d0(S2M_FormatLocalBuffer_U0_axi_elt_dma_buffer_V_d0)
);

DataMoverUnit_s2mm_32bits_DMAWriteMM DMAWriteMM_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(DMAWriteMM_U0_ap_start),
    .ap_done(DMAWriteMM_U0_ap_done),
    .ap_continue(DMAWriteMM_U0_ap_continue),
    .ap_idle(DMAWriteMM_U0_ap_idle),
    .ap_ready(DMAWriteMM_U0_ap_ready),
    .m_axi_MM_video_out_AWVALID(DMAWriteMM_U0_m_axi_MM_video_out_AWVALID),
    .m_axi_MM_video_out_AWREADY(m_axi_MM_video_out_AWREADY),
    .m_axi_MM_video_out_AWADDR(DMAWriteMM_U0_m_axi_MM_video_out_AWADDR),
    .m_axi_MM_video_out_AWID(DMAWriteMM_U0_m_axi_MM_video_out_AWID),
    .m_axi_MM_video_out_AWLEN(DMAWriteMM_U0_m_axi_MM_video_out_AWLEN),
    .m_axi_MM_video_out_AWSIZE(DMAWriteMM_U0_m_axi_MM_video_out_AWSIZE),
    .m_axi_MM_video_out_AWBURST(DMAWriteMM_U0_m_axi_MM_video_out_AWBURST),
    .m_axi_MM_video_out_AWLOCK(DMAWriteMM_U0_m_axi_MM_video_out_AWLOCK),
    .m_axi_MM_video_out_AWCACHE(DMAWriteMM_U0_m_axi_MM_video_out_AWCACHE),
    .m_axi_MM_video_out_AWPROT(DMAWriteMM_U0_m_axi_MM_video_out_AWPROT),
    .m_axi_MM_video_out_AWQOS(DMAWriteMM_U0_m_axi_MM_video_out_AWQOS),
    .m_axi_MM_video_out_AWREGION(DMAWriteMM_U0_m_axi_MM_video_out_AWREGION),
    .m_axi_MM_video_out_AWUSER(DMAWriteMM_U0_m_axi_MM_video_out_AWUSER),
    .m_axi_MM_video_out_WVALID(DMAWriteMM_U0_m_axi_MM_video_out_WVALID),
    .m_axi_MM_video_out_WREADY(m_axi_MM_video_out_WREADY),
    .m_axi_MM_video_out_WDATA(DMAWriteMM_U0_m_axi_MM_video_out_WDATA),
    .m_axi_MM_video_out_WSTRB(DMAWriteMM_U0_m_axi_MM_video_out_WSTRB),
    .m_axi_MM_video_out_WLAST(DMAWriteMM_U0_m_axi_MM_video_out_WLAST),
    .m_axi_MM_video_out_WID(DMAWriteMM_U0_m_axi_MM_video_out_WID),
    .m_axi_MM_video_out_WUSER(DMAWriteMM_U0_m_axi_MM_video_out_WUSER),
    .m_axi_MM_video_out_ARVALID(DMAWriteMM_U0_m_axi_MM_video_out_ARVALID),
    .m_axi_MM_video_out_ARREADY(1'b0),
    .m_axi_MM_video_out_ARADDR(DMAWriteMM_U0_m_axi_MM_video_out_ARADDR),
    .m_axi_MM_video_out_ARID(DMAWriteMM_U0_m_axi_MM_video_out_ARID),
    .m_axi_MM_video_out_ARLEN(DMAWriteMM_U0_m_axi_MM_video_out_ARLEN),
    .m_axi_MM_video_out_ARSIZE(DMAWriteMM_U0_m_axi_MM_video_out_ARSIZE),
    .m_axi_MM_video_out_ARBURST(DMAWriteMM_U0_m_axi_MM_video_out_ARBURST),
    .m_axi_MM_video_out_ARLOCK(DMAWriteMM_U0_m_axi_MM_video_out_ARLOCK),
    .m_axi_MM_video_out_ARCACHE(DMAWriteMM_U0_m_axi_MM_video_out_ARCACHE),
    .m_axi_MM_video_out_ARPROT(DMAWriteMM_U0_m_axi_MM_video_out_ARPROT),
    .m_axi_MM_video_out_ARQOS(DMAWriteMM_U0_m_axi_MM_video_out_ARQOS),
    .m_axi_MM_video_out_ARREGION(DMAWriteMM_U0_m_axi_MM_video_out_ARREGION),
    .m_axi_MM_video_out_ARUSER(DMAWriteMM_U0_m_axi_MM_video_out_ARUSER),
    .m_axi_MM_video_out_RVALID(1'b0),
    .m_axi_MM_video_out_RREADY(DMAWriteMM_U0_m_axi_MM_video_out_RREADY),
    .m_axi_MM_video_out_RDATA(32'd0),
    .m_axi_MM_video_out_RLAST(1'b0),
    .m_axi_MM_video_out_RID(1'd0),
    .m_axi_MM_video_out_RUSER(1'd0),
    .m_axi_MM_video_out_RRESP(2'd0),
    .m_axi_MM_video_out_BVALID(m_axi_MM_video_out_BVALID),
    .m_axi_MM_video_out_BREADY(DMAWriteMM_U0_m_axi_MM_video_out_BREADY),
    .m_axi_MM_video_out_BRESP(m_axi_MM_video_out_BRESP),
    .m_axi_MM_video_out_BID(m_axi_MM_video_out_BID),
    .m_axi_MM_video_out_BUSER(m_axi_MM_video_out_BUSER),
    .ddr_buffer_out_dout(ddr_buffer_out_c_dout),
    .ddr_buffer_out_empty_n(ddr_buffer_out_c_empty_n),
    .ddr_buffer_out_read(DMAWriteMM_U0_ddr_buffer_out_read),
    .DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_dout(DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_c_dout),
    .DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_empty_n(DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_c_empty_n),
    .DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_read(DMAWriteMM_U0_DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_read),
    .image_h_dout(image_h_c_dout),
    .image_h_empty_n(image_h_c_empty_n),
    .image_h_read(DMAWriteMM_U0_image_h_read),
    .image_w_dout(image_w_c_dout),
    .image_w_empty_n(image_w_c_empty_n),
    .image_w_read(DMAWriteMM_U0_image_w_read),
    .invert_Y_dout(invert_Y_c_dout),
    .invert_Y_empty_n(invert_Y_c_empty_n),
    .invert_Y_read(DMAWriteMM_U0_invert_Y_read),
    .axi_elt_dma_buffer_V_address0(DMAWriteMM_U0_axi_elt_dma_buffer_V_address0),
    .axi_elt_dma_buffer_V_ce0(DMAWriteMM_U0_axi_elt_dma_buffer_V_ce0),
    .axi_elt_dma_buffer_V_q0(axi_elt_dma_buffer_V_t_q0)
);

DataMoverUnit_s2mm_32bits_dataflow_in_loop_S2M_stream_elt_dma_buffer_V #(
    .DataWidth( 8 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
stream_elt_dma_buffer_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(FillLocalBuffer7_U0_stream_elt_dma_buffer_V_address0),
    .i_ce0(FillLocalBuffer7_U0_stream_elt_dma_buffer_V_ce0),
    .i_we0(FillLocalBuffer7_U0_stream_elt_dma_buffer_V_we0),
    .i_d0(FillLocalBuffer7_U0_stream_elt_dma_buffer_V_d0),
    .i_q0(stream_elt_dma_buffer_V_i_q0),
    .i_address1(11'd0),
    .i_ce1(1'b0),
    .i_q1(stream_elt_dma_buffer_V_i_q1),
    .t_address0(S2M_FormatLocalBuffer_U0_stream_elt_dma_buffer_V_address0),
    .t_ce0(S2M_FormatLocalBuffer_U0_stream_elt_dma_buffer_V_ce0),
    .t_we0(1'b0),
    .t_d0(8'd0),
    .t_q0(stream_elt_dma_buffer_V_t_q0),
    .t_address1(S2M_FormatLocalBuffer_U0_stream_elt_dma_buffer_V_address1),
    .t_ce1(S2M_FormatLocalBuffer_U0_stream_elt_dma_buffer_V_ce1),
    .t_q1(stream_elt_dma_buffer_V_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(stream_elt_dma_buffer_V_i_full_n),
    .i_write(FillLocalBuffer7_U0_ap_done),
    .t_empty_n(stream_elt_dma_buffer_V_t_empty_n),
    .t_read(S2M_FormatLocalBuffer_U0_ap_ready)
);

DataMoverUnit_s2mm_32bits_dataflow_in_loop_S2M_axi_elt_dma_buffer_V #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
axi_elt_dma_buffer_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(S2M_FormatLocalBuffer_U0_axi_elt_dma_buffer_V_address0),
    .i_ce0(S2M_FormatLocalBuffer_U0_axi_elt_dma_buffer_V_ce0),
    .i_we0(S2M_FormatLocalBuffer_U0_axi_elt_dma_buffer_V_we0),
    .i_d0(S2M_FormatLocalBuffer_U0_axi_elt_dma_buffer_V_d0),
    .i_q0(axi_elt_dma_buffer_V_i_q0),
    .t_address0(DMAWriteMM_U0_axi_elt_dma_buffer_V_address0),
    .t_ce0(DMAWriteMM_U0_axi_elt_dma_buffer_V_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(axi_elt_dma_buffer_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(axi_elt_dma_buffer_V_i_full_n),
    .i_write(S2M_FormatLocalBuffer_U0_ap_done),
    .t_empty_n(axi_elt_dma_buffer_V_t_empty_n),
    .t_read(DMAWriteMM_U0_ap_ready)
);

DataMoverUnit_s2mm_32bits_fifo_w32_d2_S image_w_c1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_S2M_entry4_U0_image_w_out_din),
    .if_full_n(image_w_c1_full_n),
    .if_write(dataflow_in_loop_S2M_entry4_U0_image_w_out_write),
    .if_dout(image_w_c1_dout),
    .if_empty_n(image_w_c1_empty_n),
    .if_read(FillLocalBuffer7_U0_image_w_read)
);

DataMoverUnit_s2mm_32bits_fifo_w1_d2_S invert_X_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_S2M_entry4_U0_invert_X_out_din),
    .if_full_n(invert_X_c_full_n),
    .if_write(dataflow_in_loop_S2M_entry4_U0_invert_X_out_write),
    .if_dout(invert_X_c_dout),
    .if_empty_n(invert_X_c_empty_n),
    .if_read(FillLocalBuffer7_U0_invert_X_read)
);

DataMoverUnit_s2mm_32bits_fifo_w32_d2_S ddr_buffer_out_c2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_S2M_entry4_U0_ddr_buffer_out_out_din),
    .if_full_n(ddr_buffer_out_c2_full_n),
    .if_write(dataflow_in_loop_S2M_entry4_U0_ddr_buffer_out_out_write),
    .if_dout(ddr_buffer_out_c2_dout),
    .if_empty_n(ddr_buffer_out_c2_empty_n),
    .if_read(FillLocalBuffer7_U0_ddr_buffer_out_read)
);

DataMoverUnit_s2mm_32bits_fifo_w31_d2_S DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_c3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_S2M_entry4_U0_DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_din),
    .if_full_n(DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_c3_full_n),
    .if_write(dataflow_in_loop_S2M_entry4_U0_DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_write),
    .if_dout(DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_c3_dout),
    .if_empty_n(DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_c3_empty_n),
    .if_read(FillLocalBuffer7_U0_DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_read)
);

DataMoverUnit_s2mm_32bits_fifo_w21_d2_S image_h_c4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_S2M_entry4_U0_image_h_out_din),
    .if_full_n(image_h_c4_full_n),
    .if_write(dataflow_in_loop_S2M_entry4_U0_image_h_out_write),
    .if_dout(image_h_c4_dout),
    .if_empty_n(image_h_c4_empty_n),
    .if_read(FillLocalBuffer7_U0_image_h_read)
);

DataMoverUnit_s2mm_32bits_fifo_w1_d2_S invert_Y_c5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_S2M_entry4_U0_invert_Y_out_din),
    .if_full_n(invert_Y_c5_full_n),
    .if_write(dataflow_in_loop_S2M_entry4_U0_invert_Y_out_write),
    .if_dout(invert_Y_c5_dout),
    .if_empty_n(invert_Y_c5_empty_n),
    .if_read(FillLocalBuffer7_U0_invert_Y_read)
);

DataMoverUnit_s2mm_32bits_fifo_w32_d3_S image_w_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(FillLocalBuffer7_U0_image_w_c_din),
    .if_full_n(image_w_c_full_n),
    .if_write(FillLocalBuffer7_U0_image_w_c_write),
    .if_dout(image_w_c_dout),
    .if_empty_n(image_w_c_empty_n),
    .if_read(DMAWriteMM_U0_image_w_read)
);

DataMoverUnit_s2mm_32bits_fifo_w32_d3_S ddr_buffer_out_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(FillLocalBuffer7_U0_ddr_buffer_out_c_din),
    .if_full_n(ddr_buffer_out_c_full_n),
    .if_write(FillLocalBuffer7_U0_ddr_buffer_out_c_write),
    .if_dout(ddr_buffer_out_c_dout),
    .if_empty_n(ddr_buffer_out_c_empty_n),
    .if_read(DMAWriteMM_U0_ddr_buffer_out_read)
);

DataMoverUnit_s2mm_32bits_fifo_w21_d3_S DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(FillLocalBuffer7_U0_DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_c_din),
    .if_full_n(DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_c_full_n),
    .if_write(FillLocalBuffer7_U0_DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_c_write),
    .if_dout(DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_c_dout),
    .if_empty_n(DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_c_empty_n),
    .if_read(DMAWriteMM_U0_DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_read)
);

DataMoverUnit_s2mm_32bits_fifo_w21_d3_S image_h_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(FillLocalBuffer7_U0_image_h_c_din),
    .if_full_n(image_h_c_full_n),
    .if_write(FillLocalBuffer7_U0_image_h_c_write),
    .if_dout(image_h_c_dout),
    .if_empty_n(image_h_c_empty_n),
    .if_read(DMAWriteMM_U0_image_h_read)
);

DataMoverUnit_s2mm_32bits_fifo_w1_d3_S invert_Y_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(FillLocalBuffer7_U0_invert_Y_c_din),
    .if_full_n(invert_Y_c_full_n),
    .if_write(FillLocalBuffer7_U0_invert_Y_c_write),
    .if_dout(invert_Y_c_dout),
    .if_empty_n(invert_Y_c_empty_n),
    .if_read(DMAWriteMM_U0_invert_Y_read)
);

DataMoverUnit_s2mm_32bits_start_for_FillLocalBuffer7_U0 start_for_FillLocalBuffer7_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_FillLocalBuffer7_U0_din),
    .if_full_n(start_for_FillLocalBuffer7_U0_full_n),
    .if_write(dataflow_in_loop_S2M_entry4_U0_start_write),
    .if_dout(start_for_FillLocalBuffer7_U0_dout),
    .if_empty_n(start_for_FillLocalBuffer7_U0_empty_n),
    .if_read(FillLocalBuffer7_U0_ap_ready)
);

assign DMAWriteMM_U0_ap_continue = ap_continue;

assign DMAWriteMM_U0_ap_start = axi_elt_dma_buffer_V_t_empty_n;

assign DMAWriteMM_U0_start_full_n = 1'b1;

assign DMAWriteMM_U0_start_write = 1'b0;

assign FillLocalBuffer7_U0_ap_continue = stream_elt_dma_buffer_V_i_full_n;

assign FillLocalBuffer7_U0_ap_start = start_for_FillLocalBuffer7_U0_empty_n;

assign FillLocalBuffer7_U0_start_full_n = 1'b1;

assign FillLocalBuffer7_U0_start_write = 1'b0;

assign FillLocalBuffer7_U0_stream_elt_dma_buffer_V_full_n = stream_elt_dma_buffer_V_i_full_n;

assign S2M_FormatLocalBuffer_U0_ap_continue = axi_elt_dma_buffer_V_i_full_n;

assign S2M_FormatLocalBuffer_U0_ap_start = stream_elt_dma_buffer_V_t_empty_n;

assign S2M_FormatLocalBuffer_U0_axi_elt_dma_buffer_V_full_n = axi_elt_dma_buffer_V_i_full_n;

assign S2M_FormatLocalBuffer_U0_start_full_n = 1'b1;

assign S2M_FormatLocalBuffer_U0_start_write = 1'b0;

assign STR_video_in_TREADY = FillLocalBuffer7_U0_STR_video_in_TREADY;

assign ap_channel_done_axi_elt_dma_buffer_V = S2M_FormatLocalBuffer_U0_ap_done;

assign ap_channel_done_stream_elt_dma_buffer_V = FillLocalBuffer7_U0_ap_done;

assign ap_done = DMAWriteMM_U0_ap_done;

assign ap_idle = ((axi_elt_dma_buffer_V_t_empty_n ^ 1'b1) & (stream_elt_dma_buffer_V_t_empty_n ^ 1'b1) & dataflow_in_loop_S2M_entry4_U0_ap_idle & S2M_FormatLocalBuffer_U0_ap_idle & FillLocalBuffer7_U0_ap_idle & DMAWriteMM_U0_ap_idle);

assign ap_ready = dataflow_in_loop_S2M_entry4_U0_ap_ready;

assign ap_sync_continue = ap_continue;

assign ap_sync_done = DMAWriteMM_U0_ap_done;

assign ap_sync_ready = dataflow_in_loop_S2M_entry4_U0_ap_ready;

assign dataflow_in_loop_S2M_entry4_U0_ap_continue = 1'b1;

assign dataflow_in_loop_S2M_entry4_U0_ap_start = ap_start;

assign m_axi_MM_video_out_ARADDR = 32'd0;

assign m_axi_MM_video_out_ARBURST = 2'd0;

assign m_axi_MM_video_out_ARCACHE = 4'd0;

assign m_axi_MM_video_out_ARID = 1'd0;

assign m_axi_MM_video_out_ARLEN = 32'd0;

assign m_axi_MM_video_out_ARLOCK = 2'd0;

assign m_axi_MM_video_out_ARPROT = 3'd0;

assign m_axi_MM_video_out_ARQOS = 4'd0;

assign m_axi_MM_video_out_ARREGION = 4'd0;

assign m_axi_MM_video_out_ARSIZE = 3'd0;

assign m_axi_MM_video_out_ARUSER = 1'd0;

assign m_axi_MM_video_out_ARVALID = 1'b0;

assign m_axi_MM_video_out_AWADDR = DMAWriteMM_U0_m_axi_MM_video_out_AWADDR;

assign m_axi_MM_video_out_AWBURST = DMAWriteMM_U0_m_axi_MM_video_out_AWBURST;

assign m_axi_MM_video_out_AWCACHE = DMAWriteMM_U0_m_axi_MM_video_out_AWCACHE;

assign m_axi_MM_video_out_AWID = DMAWriteMM_U0_m_axi_MM_video_out_AWID;

assign m_axi_MM_video_out_AWLEN = DMAWriteMM_U0_m_axi_MM_video_out_AWLEN;

assign m_axi_MM_video_out_AWLOCK = DMAWriteMM_U0_m_axi_MM_video_out_AWLOCK;

assign m_axi_MM_video_out_AWPROT = DMAWriteMM_U0_m_axi_MM_video_out_AWPROT;

assign m_axi_MM_video_out_AWQOS = DMAWriteMM_U0_m_axi_MM_video_out_AWQOS;

assign m_axi_MM_video_out_AWREGION = DMAWriteMM_U0_m_axi_MM_video_out_AWREGION;

assign m_axi_MM_video_out_AWSIZE = DMAWriteMM_U0_m_axi_MM_video_out_AWSIZE;

assign m_axi_MM_video_out_AWUSER = DMAWriteMM_U0_m_axi_MM_video_out_AWUSER;

assign m_axi_MM_video_out_AWVALID = DMAWriteMM_U0_m_axi_MM_video_out_AWVALID;

assign m_axi_MM_video_out_BREADY = DMAWriteMM_U0_m_axi_MM_video_out_BREADY;

assign m_axi_MM_video_out_RREADY = 1'b0;

assign m_axi_MM_video_out_WDATA = DMAWriteMM_U0_m_axi_MM_video_out_WDATA;

assign m_axi_MM_video_out_WID = DMAWriteMM_U0_m_axi_MM_video_out_WID;

assign m_axi_MM_video_out_WLAST = DMAWriteMM_U0_m_axi_MM_video_out_WLAST;

assign m_axi_MM_video_out_WSTRB = DMAWriteMM_U0_m_axi_MM_video_out_WSTRB;

assign m_axi_MM_video_out_WUSER = DMAWriteMM_U0_m_axi_MM_video_out_WUSER;

assign m_axi_MM_video_out_WVALID = DMAWriteMM_U0_m_axi_MM_video_out_WVALID;

assign start_for_FillLocalBuffer7_U0_din = 1'b1;

assign stream_elt_dma_buffer_V_t_d1 = 8'd0;

assign stream_elt_dma_buffer_V_t_we1 = 1'b0;

endmodule //DataMoverUnit_s2mm_32bits_dataflow_in_loop_S2M
