// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="CornerResponseUnit_CornerResponseUnit,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.297000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1763,HLS_SYN_LUT=2476,HLS_VERSION=2020_2}" *)

module CornerResponseUnit (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        stream_in_1_TDATA,
        stream_in_1_TVALID,
        stream_in_1_TREADY,
        stream_in_1_TKEEP,
        stream_in_1_TSTRB,
        stream_in_1_TUSER,
        stream_in_1_TLAST,
        stream_in_2_TDATA,
        stream_in_2_TVALID,
        stream_in_2_TREADY,
        stream_in_2_TKEEP,
        stream_in_2_TSTRB,
        stream_in_2_TUSER,
        stream_in_2_TLAST,
        stream_in_3_TDATA,
        stream_in_3_TVALID,
        stream_in_3_TREADY,
        stream_in_3_TKEEP,
        stream_in_3_TSTRB,
        stream_in_3_TUSER,
        stream_in_3_TLAST,
        stream_out_TDATA,
        stream_out_TVALID,
        stream_out_TREADY,
        stream_out_TKEEP,
        stream_out_TSTRB,
        stream_out_TUSER,
        stream_out_TLAST,
        image_w,
        image_h
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] stream_in_1_TDATA;
input   stream_in_1_TVALID;
output   stream_in_1_TREADY;
input  [1:0] stream_in_1_TKEEP;
input  [1:0] stream_in_1_TSTRB;
input  [0:0] stream_in_1_TUSER;
input  [0:0] stream_in_1_TLAST;
input  [15:0] stream_in_2_TDATA;
input   stream_in_2_TVALID;
output   stream_in_2_TREADY;
input  [1:0] stream_in_2_TKEEP;
input  [1:0] stream_in_2_TSTRB;
input  [0:0] stream_in_2_TUSER;
input  [0:0] stream_in_2_TLAST;
input  [15:0] stream_in_3_TDATA;
input   stream_in_3_TVALID;
output   stream_in_3_TREADY;
input  [1:0] stream_in_3_TKEEP;
input  [1:0] stream_in_3_TSTRB;
input  [0:0] stream_in_3_TUSER;
input  [0:0] stream_in_3_TLAST;
output  [15:0] stream_out_TDATA;
output   stream_out_TVALID;
input   stream_out_TREADY;
output  [1:0] stream_out_TKEEP;
output  [1:0] stream_out_TSTRB;
output  [0:0] stream_out_TUSER;
output  [0:0] stream_out_TLAST;
input  [31:0] image_w;
input  [31:0] image_h;

reg ap_done;
reg ap_idle;
reg ap_ready;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state2;
wire    grp_CornerResponse_fu_80_ap_start;
wire    grp_CornerResponse_fu_80_ap_done;
wire    grp_CornerResponse_fu_80_ap_idle;
wire    grp_CornerResponse_fu_80_ap_ready;
wire    grp_CornerResponse_fu_80_stream_in_1_TREADY;
wire    grp_CornerResponse_fu_80_stream_in_2_TREADY;
wire    grp_CornerResponse_fu_80_stream_in_3_TREADY;
wire   [15:0] grp_CornerResponse_fu_80_stream_out_TDATA;
wire    grp_CornerResponse_fu_80_stream_out_TVALID;
wire    grp_CornerResponse_fu_80_stream_out_TREADY;
wire   [1:0] grp_CornerResponse_fu_80_stream_out_TKEEP;
wire   [1:0] grp_CornerResponse_fu_80_stream_out_TSTRB;
wire   [0:0] grp_CornerResponse_fu_80_stream_out_TUSER;
wire   [0:0] grp_CornerResponse_fu_80_stream_out_TLAST;
reg    grp_CornerResponse_fu_80_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    regslice_both_stream_out_V_data_V_U_apdone_blk;
reg   [3:0] ap_NS_fsm;
wire    regslice_both_stream_in_1_V_data_V_U_apdone_blk;
wire   [15:0] stream_in_1_TDATA_int_regslice;
wire    stream_in_1_TVALID_int_regslice;
reg    stream_in_1_TREADY_int_regslice;
wire    regslice_both_stream_in_1_V_data_V_U_ack_in;
wire    regslice_both_stream_in_1_V_keep_V_U_apdone_blk;
wire   [1:0] stream_in_1_TKEEP_int_regslice;
wire    regslice_both_stream_in_1_V_keep_V_U_vld_out;
wire    regslice_both_stream_in_1_V_keep_V_U_ack_in;
wire    regslice_both_stream_in_1_V_strb_V_U_apdone_blk;
wire   [1:0] stream_in_1_TSTRB_int_regslice;
wire    regslice_both_stream_in_1_V_strb_V_U_vld_out;
wire    regslice_both_stream_in_1_V_strb_V_U_ack_in;
wire    regslice_both_stream_in_1_V_user_V_U_apdone_blk;
wire   [0:0] stream_in_1_TUSER_int_regslice;
wire    regslice_both_stream_in_1_V_user_V_U_vld_out;
wire    regslice_both_stream_in_1_V_user_V_U_ack_in;
wire    regslice_both_stream_in_1_V_last_V_U_apdone_blk;
wire   [0:0] stream_in_1_TLAST_int_regslice;
wire    regslice_both_stream_in_1_V_last_V_U_vld_out;
wire    regslice_both_stream_in_1_V_last_V_U_ack_in;
wire    regslice_both_stream_in_2_V_data_V_U_apdone_blk;
wire   [15:0] stream_in_2_TDATA_int_regslice;
wire    stream_in_2_TVALID_int_regslice;
reg    stream_in_2_TREADY_int_regslice;
wire    regslice_both_stream_in_2_V_data_V_U_ack_in;
wire    regslice_both_stream_in_2_V_keep_V_U_apdone_blk;
wire   [1:0] stream_in_2_TKEEP_int_regslice;
wire    regslice_both_stream_in_2_V_keep_V_U_vld_out;
wire    regslice_both_stream_in_2_V_keep_V_U_ack_in;
wire    regslice_both_stream_in_2_V_strb_V_U_apdone_blk;
wire   [1:0] stream_in_2_TSTRB_int_regslice;
wire    regslice_both_stream_in_2_V_strb_V_U_vld_out;
wire    regslice_both_stream_in_2_V_strb_V_U_ack_in;
wire    regslice_both_stream_in_2_V_user_V_U_apdone_blk;
wire   [0:0] stream_in_2_TUSER_int_regslice;
wire    regslice_both_stream_in_2_V_user_V_U_vld_out;
wire    regslice_both_stream_in_2_V_user_V_U_ack_in;
wire    regslice_both_stream_in_2_V_last_V_U_apdone_blk;
wire   [0:0] stream_in_2_TLAST_int_regslice;
wire    regslice_both_stream_in_2_V_last_V_U_vld_out;
wire    regslice_both_stream_in_2_V_last_V_U_ack_in;
wire    regslice_both_stream_in_3_V_data_V_U_apdone_blk;
wire   [15:0] stream_in_3_TDATA_int_regslice;
wire    stream_in_3_TVALID_int_regslice;
reg    stream_in_3_TREADY_int_regslice;
wire    regslice_both_stream_in_3_V_data_V_U_ack_in;
wire    regslice_both_stream_in_3_V_keep_V_U_apdone_blk;
wire   [1:0] stream_in_3_TKEEP_int_regslice;
wire    regslice_both_stream_in_3_V_keep_V_U_vld_out;
wire    regslice_both_stream_in_3_V_keep_V_U_ack_in;
wire    regslice_both_stream_in_3_V_strb_V_U_apdone_blk;
wire   [1:0] stream_in_3_TSTRB_int_regslice;
wire    regslice_both_stream_in_3_V_strb_V_U_vld_out;
wire    regslice_both_stream_in_3_V_strb_V_U_ack_in;
wire    regslice_both_stream_in_3_V_user_V_U_apdone_blk;
wire   [0:0] stream_in_3_TUSER_int_regslice;
wire    regslice_both_stream_in_3_V_user_V_U_vld_out;
wire    regslice_both_stream_in_3_V_user_V_U_ack_in;
wire    regslice_both_stream_in_3_V_last_V_U_apdone_blk;
wire   [0:0] stream_in_3_TLAST_int_regslice;
wire    regslice_both_stream_in_3_V_last_V_U_vld_out;
wire    regslice_both_stream_in_3_V_last_V_U_ack_in;
wire    stream_out_TREADY_int_regslice;
wire    regslice_both_stream_out_V_data_V_U_vld_out;
wire    regslice_both_stream_out_V_keep_V_U_apdone_blk;
wire    regslice_both_stream_out_V_keep_V_U_ack_in_dummy;
wire    regslice_both_stream_out_V_keep_V_U_vld_out;
wire    regslice_both_stream_out_V_strb_V_U_apdone_blk;
wire    regslice_both_stream_out_V_strb_V_U_ack_in_dummy;
wire    regslice_both_stream_out_V_strb_V_U_vld_out;
wire    regslice_both_stream_out_V_user_V_U_apdone_blk;
wire    regslice_both_stream_out_V_user_V_U_ack_in_dummy;
wire    regslice_both_stream_out_V_user_V_U_vld_out;
wire    regslice_both_stream_out_V_last_V_U_apdone_blk;
wire    regslice_both_stream_out_V_last_V_U_ack_in_dummy;
wire    regslice_both_stream_out_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_CornerResponse_fu_80_ap_start_reg = 1'b0;
end

CornerResponseUnit_CornerResponse grp_CornerResponse_fu_80(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_CornerResponse_fu_80_ap_start),
    .ap_done(grp_CornerResponse_fu_80_ap_done),
    .ap_idle(grp_CornerResponse_fu_80_ap_idle),
    .ap_ready(grp_CornerResponse_fu_80_ap_ready),
    .stream_in_1_TDATA(stream_in_1_TDATA_int_regslice),
    .stream_in_1_TVALID(stream_in_1_TVALID_int_regslice),
    .stream_in_1_TREADY(grp_CornerResponse_fu_80_stream_in_1_TREADY),
    .stream_in_1_TKEEP(stream_in_1_TKEEP_int_regslice),
    .stream_in_1_TSTRB(stream_in_1_TSTRB_int_regslice),
    .stream_in_1_TUSER(stream_in_1_TUSER_int_regslice),
    .stream_in_1_TLAST(stream_in_1_TLAST_int_regslice),
    .stream_in_2_TDATA(stream_in_2_TDATA_int_regslice),
    .stream_in_2_TVALID(stream_in_2_TVALID_int_regslice),
    .stream_in_2_TREADY(grp_CornerResponse_fu_80_stream_in_2_TREADY),
    .stream_in_2_TKEEP(stream_in_2_TKEEP_int_regslice),
    .stream_in_2_TSTRB(stream_in_2_TSTRB_int_regslice),
    .stream_in_2_TUSER(stream_in_2_TUSER_int_regslice),
    .stream_in_2_TLAST(stream_in_2_TLAST_int_regslice),
    .stream_in_3_TDATA(stream_in_3_TDATA_int_regslice),
    .stream_in_3_TVALID(stream_in_3_TVALID_int_regslice),
    .stream_in_3_TREADY(grp_CornerResponse_fu_80_stream_in_3_TREADY),
    .stream_in_3_TKEEP(stream_in_3_TKEEP_int_regslice),
    .stream_in_3_TSTRB(stream_in_3_TSTRB_int_regslice),
    .stream_in_3_TUSER(stream_in_3_TUSER_int_regslice),
    .stream_in_3_TLAST(stream_in_3_TLAST_int_regslice),
    .stream_out_TDATA(grp_CornerResponse_fu_80_stream_out_TDATA),
    .stream_out_TVALID(grp_CornerResponse_fu_80_stream_out_TVALID),
    .stream_out_TREADY(grp_CornerResponse_fu_80_stream_out_TREADY),
    .stream_out_TKEEP(grp_CornerResponse_fu_80_stream_out_TKEEP),
    .stream_out_TSTRB(grp_CornerResponse_fu_80_stream_out_TSTRB),
    .stream_out_TUSER(grp_CornerResponse_fu_80_stream_out_TUSER),
    .stream_out_TLAST(grp_CornerResponse_fu_80_stream_out_TLAST),
    .image_w(image_w),
    .image_h(image_h)
);

CornerResponseUnit_regslice_both #(
    .DataWidth( 16 ))
regslice_both_stream_in_1_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_1_TDATA),
    .vld_in(stream_in_1_TVALID),
    .ack_in(regslice_both_stream_in_1_V_data_V_U_ack_in),
    .data_out(stream_in_1_TDATA_int_regslice),
    .vld_out(stream_in_1_TVALID_int_regslice),
    .ack_out(stream_in_1_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_1_V_data_V_U_apdone_blk)
);

CornerResponseUnit_regslice_both #(
    .DataWidth( 2 ))
regslice_both_stream_in_1_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_1_TKEEP),
    .vld_in(stream_in_1_TVALID),
    .ack_in(regslice_both_stream_in_1_V_keep_V_U_ack_in),
    .data_out(stream_in_1_TKEEP_int_regslice),
    .vld_out(regslice_both_stream_in_1_V_keep_V_U_vld_out),
    .ack_out(stream_in_1_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_1_V_keep_V_U_apdone_blk)
);

CornerResponseUnit_regslice_both #(
    .DataWidth( 2 ))
regslice_both_stream_in_1_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_1_TSTRB),
    .vld_in(stream_in_1_TVALID),
    .ack_in(regslice_both_stream_in_1_V_strb_V_U_ack_in),
    .data_out(stream_in_1_TSTRB_int_regslice),
    .vld_out(regslice_both_stream_in_1_V_strb_V_U_vld_out),
    .ack_out(stream_in_1_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_1_V_strb_V_U_apdone_blk)
);

CornerResponseUnit_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_in_1_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_1_TUSER),
    .vld_in(stream_in_1_TVALID),
    .ack_in(regslice_both_stream_in_1_V_user_V_U_ack_in),
    .data_out(stream_in_1_TUSER_int_regslice),
    .vld_out(regslice_both_stream_in_1_V_user_V_U_vld_out),
    .ack_out(stream_in_1_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_1_V_user_V_U_apdone_blk)
);

CornerResponseUnit_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_in_1_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_1_TLAST),
    .vld_in(stream_in_1_TVALID),
    .ack_in(regslice_both_stream_in_1_V_last_V_U_ack_in),
    .data_out(stream_in_1_TLAST_int_regslice),
    .vld_out(regslice_both_stream_in_1_V_last_V_U_vld_out),
    .ack_out(stream_in_1_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_1_V_last_V_U_apdone_blk)
);

CornerResponseUnit_regslice_both #(
    .DataWidth( 16 ))
regslice_both_stream_in_2_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_2_TDATA),
    .vld_in(stream_in_2_TVALID),
    .ack_in(regslice_both_stream_in_2_V_data_V_U_ack_in),
    .data_out(stream_in_2_TDATA_int_regslice),
    .vld_out(stream_in_2_TVALID_int_regslice),
    .ack_out(stream_in_2_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_2_V_data_V_U_apdone_blk)
);

CornerResponseUnit_regslice_both #(
    .DataWidth( 2 ))
regslice_both_stream_in_2_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_2_TKEEP),
    .vld_in(stream_in_2_TVALID),
    .ack_in(regslice_both_stream_in_2_V_keep_V_U_ack_in),
    .data_out(stream_in_2_TKEEP_int_regslice),
    .vld_out(regslice_both_stream_in_2_V_keep_V_U_vld_out),
    .ack_out(stream_in_2_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_2_V_keep_V_U_apdone_blk)
);

CornerResponseUnit_regslice_both #(
    .DataWidth( 2 ))
regslice_both_stream_in_2_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_2_TSTRB),
    .vld_in(stream_in_2_TVALID),
    .ack_in(regslice_both_stream_in_2_V_strb_V_U_ack_in),
    .data_out(stream_in_2_TSTRB_int_regslice),
    .vld_out(regslice_both_stream_in_2_V_strb_V_U_vld_out),
    .ack_out(stream_in_2_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_2_V_strb_V_U_apdone_blk)
);

CornerResponseUnit_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_in_2_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_2_TUSER),
    .vld_in(stream_in_2_TVALID),
    .ack_in(regslice_both_stream_in_2_V_user_V_U_ack_in),
    .data_out(stream_in_2_TUSER_int_regslice),
    .vld_out(regslice_both_stream_in_2_V_user_V_U_vld_out),
    .ack_out(stream_in_2_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_2_V_user_V_U_apdone_blk)
);

CornerResponseUnit_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_in_2_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_2_TLAST),
    .vld_in(stream_in_2_TVALID),
    .ack_in(regslice_both_stream_in_2_V_last_V_U_ack_in),
    .data_out(stream_in_2_TLAST_int_regslice),
    .vld_out(regslice_both_stream_in_2_V_last_V_U_vld_out),
    .ack_out(stream_in_2_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_2_V_last_V_U_apdone_blk)
);

CornerResponseUnit_regslice_both #(
    .DataWidth( 16 ))
regslice_both_stream_in_3_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_3_TDATA),
    .vld_in(stream_in_3_TVALID),
    .ack_in(regslice_both_stream_in_3_V_data_V_U_ack_in),
    .data_out(stream_in_3_TDATA_int_regslice),
    .vld_out(stream_in_3_TVALID_int_regslice),
    .ack_out(stream_in_3_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_3_V_data_V_U_apdone_blk)
);

CornerResponseUnit_regslice_both #(
    .DataWidth( 2 ))
regslice_both_stream_in_3_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_3_TKEEP),
    .vld_in(stream_in_3_TVALID),
    .ack_in(regslice_both_stream_in_3_V_keep_V_U_ack_in),
    .data_out(stream_in_3_TKEEP_int_regslice),
    .vld_out(regslice_both_stream_in_3_V_keep_V_U_vld_out),
    .ack_out(stream_in_3_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_3_V_keep_V_U_apdone_blk)
);

CornerResponseUnit_regslice_both #(
    .DataWidth( 2 ))
regslice_both_stream_in_3_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_3_TSTRB),
    .vld_in(stream_in_3_TVALID),
    .ack_in(regslice_both_stream_in_3_V_strb_V_U_ack_in),
    .data_out(stream_in_3_TSTRB_int_regslice),
    .vld_out(regslice_both_stream_in_3_V_strb_V_U_vld_out),
    .ack_out(stream_in_3_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_3_V_strb_V_U_apdone_blk)
);

CornerResponseUnit_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_in_3_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_3_TUSER),
    .vld_in(stream_in_3_TVALID),
    .ack_in(regslice_both_stream_in_3_V_user_V_U_ack_in),
    .data_out(stream_in_3_TUSER_int_regslice),
    .vld_out(regslice_both_stream_in_3_V_user_V_U_vld_out),
    .ack_out(stream_in_3_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_3_V_user_V_U_apdone_blk)
);

CornerResponseUnit_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_in_3_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(stream_in_3_TLAST),
    .vld_in(stream_in_3_TVALID),
    .ack_in(regslice_both_stream_in_3_V_last_V_U_ack_in),
    .data_out(stream_in_3_TLAST_int_regslice),
    .vld_out(regslice_both_stream_in_3_V_last_V_U_vld_out),
    .ack_out(stream_in_3_TREADY_int_regslice),
    .apdone_blk(regslice_both_stream_in_3_V_last_V_U_apdone_blk)
);

CornerResponseUnit_regslice_both #(
    .DataWidth( 16 ))
regslice_both_stream_out_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_CornerResponse_fu_80_stream_out_TDATA),
    .vld_in(grp_CornerResponse_fu_80_stream_out_TVALID),
    .ack_in(stream_out_TREADY_int_regslice),
    .data_out(stream_out_TDATA),
    .vld_out(regslice_both_stream_out_V_data_V_U_vld_out),
    .ack_out(stream_out_TREADY),
    .apdone_blk(regslice_both_stream_out_V_data_V_U_apdone_blk)
);

CornerResponseUnit_regslice_both #(
    .DataWidth( 2 ))
regslice_both_stream_out_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_CornerResponse_fu_80_stream_out_TKEEP),
    .vld_in(grp_CornerResponse_fu_80_stream_out_TVALID),
    .ack_in(regslice_both_stream_out_V_keep_V_U_ack_in_dummy),
    .data_out(stream_out_TKEEP),
    .vld_out(regslice_both_stream_out_V_keep_V_U_vld_out),
    .ack_out(stream_out_TREADY),
    .apdone_blk(regslice_both_stream_out_V_keep_V_U_apdone_blk)
);

CornerResponseUnit_regslice_both #(
    .DataWidth( 2 ))
regslice_both_stream_out_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_CornerResponse_fu_80_stream_out_TSTRB),
    .vld_in(grp_CornerResponse_fu_80_stream_out_TVALID),
    .ack_in(regslice_both_stream_out_V_strb_V_U_ack_in_dummy),
    .data_out(stream_out_TSTRB),
    .vld_out(regslice_both_stream_out_V_strb_V_U_vld_out),
    .ack_out(stream_out_TREADY),
    .apdone_blk(regslice_both_stream_out_V_strb_V_U_apdone_blk)
);

CornerResponseUnit_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_out_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_CornerResponse_fu_80_stream_out_TUSER),
    .vld_in(grp_CornerResponse_fu_80_stream_out_TVALID),
    .ack_in(regslice_both_stream_out_V_user_V_U_ack_in_dummy),
    .data_out(stream_out_TUSER),
    .vld_out(regslice_both_stream_out_V_user_V_U_vld_out),
    .ack_out(stream_out_TREADY),
    .apdone_blk(regslice_both_stream_out_V_user_V_U_apdone_blk)
);

CornerResponseUnit_regslice_both #(
    .DataWidth( 1 ))
regslice_both_stream_out_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_CornerResponse_fu_80_stream_out_TLAST),
    .vld_in(grp_CornerResponse_fu_80_stream_out_TVALID),
    .ack_in(regslice_both_stream_out_V_last_V_U_ack_in_dummy),
    .data_out(stream_out_TLAST),
    .vld_out(regslice_both_stream_out_V_last_V_U_vld_out),
    .ack_out(stream_out_TREADY),
    .apdone_blk(regslice_both_stream_out_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_CornerResponse_fu_80_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_CornerResponse_fu_80_ap_start_reg <= 1'b1;
        end else if ((grp_CornerResponse_fu_80_ap_ready == 1'b1)) begin
            grp_CornerResponse_fu_80_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_stream_out_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_stream_out_V_data_V_U_apdone_blk == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        stream_in_1_TREADY_int_regslice = grp_CornerResponse_fu_80_stream_in_1_TREADY;
    end else begin
        stream_in_1_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        stream_in_2_TREADY_int_regslice = grp_CornerResponse_fu_80_stream_in_2_TREADY;
    end else begin
        stream_in_2_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        stream_in_3_TREADY_int_regslice = grp_CornerResponse_fu_80_stream_in_3_TREADY;
    end else begin
        stream_in_3_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_CornerResponse_fu_80_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (regslice_both_stream_out_V_data_V_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_CornerResponse_fu_80_ap_start = grp_CornerResponse_fu_80_ap_start_reg;

assign grp_CornerResponse_fu_80_stream_out_TREADY = (stream_out_TREADY_int_regslice & ap_CS_fsm_state3);

assign stream_in_1_TREADY = regslice_both_stream_in_1_V_data_V_U_ack_in;

assign stream_in_2_TREADY = regslice_both_stream_in_2_V_data_V_U_ack_in;

assign stream_in_3_TREADY = regslice_both_stream_in_3_V_data_V_U_ack_in;

assign stream_out_TVALID = regslice_both_stream_out_V_data_V_U_vld_out;

endmodule //CornerResponseUnit
