set_false_path -through [get_ports image_w[*]]
set_false_path -through [get_ports image_h[*]]
set_false_path -through [get_ports alpha[*]]
set_false_path -through [get_ports beta[*]]
set_false_path -through [get_ports max_response[*]]
