#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("stream_in_1_TDATA", 16, hls_in, 0, "axis", "in_data", 1),
	Port_Property("stream_in_1_TVALID", 1, hls_in, 4, "axis", "in_vld", 1),
	Port_Property("stream_in_1_TREADY", 1, hls_out, 4, "axis", "in_acc", 1),
	Port_Property("stream_in_1_TKEEP", 2, hls_in, 1, "axis", "in_data", 1),
	Port_Property("stream_in_1_TSTRB", 2, hls_in, 2, "axis", "in_data", 1),
	Port_Property("stream_in_1_TUSER", 1, hls_in, 3, "axis", "in_data", 1),
	Port_Property("stream_in_1_TLAST", 1, hls_in, 4, "axis", "in_data", 1),
	Port_Property("stream_in_2_TDATA", 16, hls_in, 5, "axis", "in_data", 1),
	Port_Property("stream_in_2_TVALID", 1, hls_in, 9, "axis", "in_vld", 1),
	Port_Property("stream_in_2_TREADY", 1, hls_out, 9, "axis", "in_acc", 1),
	Port_Property("stream_in_2_TKEEP", 2, hls_in, 6, "axis", "in_data", 1),
	Port_Property("stream_in_2_TSTRB", 2, hls_in, 7, "axis", "in_data", 1),
	Port_Property("stream_in_2_TUSER", 1, hls_in, 8, "axis", "in_data", 1),
	Port_Property("stream_in_2_TLAST", 1, hls_in, 9, "axis", "in_data", 1),
	Port_Property("stream_in_3_TDATA", 16, hls_in, 10, "axis", "in_data", 1),
	Port_Property("stream_in_3_TVALID", 1, hls_in, 14, "axis", "in_vld", 1),
	Port_Property("stream_in_3_TREADY", 1, hls_out, 14, "axis", "in_acc", 1),
	Port_Property("stream_in_3_TKEEP", 2, hls_in, 11, "axis", "in_data", 1),
	Port_Property("stream_in_3_TSTRB", 2, hls_in, 12, "axis", "in_data", 1),
	Port_Property("stream_in_3_TUSER", 1, hls_in, 13, "axis", "in_data", 1),
	Port_Property("stream_in_3_TLAST", 1, hls_in, 14, "axis", "in_data", 1),
	Port_Property("stream_out_TDATA", 16, hls_out, 15, "axis", "out_data", 1),
	Port_Property("stream_out_TVALID", 1, hls_out, 19, "axis", "out_vld", 1),
	Port_Property("stream_out_TREADY", 1, hls_in, 19, "axis", "out_acc", 1),
	Port_Property("stream_out_TKEEP", 2, hls_out, 16, "axis", "out_data", 1),
	Port_Property("stream_out_TSTRB", 2, hls_out, 17, "axis", "out_data", 1),
	Port_Property("stream_out_TUSER", 1, hls_out, 18, "axis", "out_data", 1),
	Port_Property("stream_out_TLAST", 1, hls_out, 19, "axis", "out_data", 1),
	Port_Property("image_w", 32, hls_in, 20, "ap_stable", "in_data", 1),
	Port_Property("image_h", 32, hls_in, 21, "ap_stable", "in_data", 1),
};
const char* HLS_Design_Meta::dut_name = "CornerResponseUnit";
