// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module DataMoverUnit_s2mm_32bits_dataflow_in_loop_S2M_entry4 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        image_w,
        invert_X,
        ddr_buffer_out,
        DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0,
        image_h,
        invert_Y,
        image_w_out_din,
        image_w_out_full_n,
        image_w_out_write,
        invert_X_out_din,
        invert_X_out_full_n,
        invert_X_out_write,
        ddr_buffer_out_out_din,
        ddr_buffer_out_out_full_n,
        ddr_buffer_out_out_write,
        DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_din,
        DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_full_n,
        DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_write,
        image_h_out_din,
        image_h_out_full_n,
        image_h_out_write,
        invert_Y_out_din,
        invert_Y_out_full_n,
        invert_Y_out_write
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] image_w;
input  [0:0] invert_X;
input  [31:0] ddr_buffer_out;
input  [30:0] DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0;
input  [20:0] image_h;
input  [0:0] invert_Y;
output  [31:0] image_w_out_din;
input   image_w_out_full_n;
output   image_w_out_write;
output  [0:0] invert_X_out_din;
input   invert_X_out_full_n;
output   invert_X_out_write;
output  [31:0] ddr_buffer_out_out_din;
input   ddr_buffer_out_out_full_n;
output   ddr_buffer_out_out_write;
output  [30:0] DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_din;
input   DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_full_n;
output   DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_write;
output  [20:0] image_h_out_din;
input   image_h_out_full_n;
output   image_h_out_write;
output  [0:0] invert_Y_out_din;
input   invert_Y_out_full_n;
output   invert_Y_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg image_w_out_write;
reg invert_X_out_write;
reg ddr_buffer_out_out_write;
reg DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_write;
reg image_h_out_write;
reg invert_Y_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    image_w_out_blk_n;
reg    invert_X_out_blk_n;
reg    ddr_buffer_out_out_blk_n;
reg    DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_blk_n;
reg    image_h_out_blk_n;
reg    invert_Y_out_blk_n;
reg    ap_block_state1;
reg   [0:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((real_start == 1'b0) | (invert_Y_out_full_n == 1'b0) | (image_h_out_full_n == 1'b0) | (ddr_buffer_out_out_full_n == 1'b0) | (invert_X_out_full_n == 1'b0) | (image_w_out_full_n == 1'b0) | (1'b0 == DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_blk_n = DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_full_n;
    end else begin
        DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (invert_Y_out_full_n == 1'b0) | (image_h_out_full_n == 1'b0) | (ddr_buffer_out_out_full_n == 1'b0) | (invert_X_out_full_n == 1'b0) | (image_w_out_full_n == 1'b0) | (1'b0 == DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_write = 1'b1;
    end else begin
        DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (invert_Y_out_full_n == 1'b0) | (image_h_out_full_n == 1'b0) | (ddr_buffer_out_out_full_n == 1'b0) | (invert_X_out_full_n == 1'b0) | (image_w_out_full_n == 1'b0) | (1'b0 == DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ddr_buffer_out_out_blk_n = ddr_buffer_out_out_full_n;
    end else begin
        ddr_buffer_out_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (invert_Y_out_full_n == 1'b0) | (image_h_out_full_n == 1'b0) | (ddr_buffer_out_out_full_n == 1'b0) | (invert_X_out_full_n == 1'b0) | (image_w_out_full_n == 1'b0) | (1'b0 == DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ddr_buffer_out_out_write = 1'b1;
    end else begin
        ddr_buffer_out_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        image_h_out_blk_n = image_h_out_full_n;
    end else begin
        image_h_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (invert_Y_out_full_n == 1'b0) | (image_h_out_full_n == 1'b0) | (ddr_buffer_out_out_full_n == 1'b0) | (invert_X_out_full_n == 1'b0) | (image_w_out_full_n == 1'b0) | (1'b0 == DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        image_h_out_write = 1'b1;
    end else begin
        image_h_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        image_w_out_blk_n = image_w_out_full_n;
    end else begin
        image_w_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (invert_Y_out_full_n == 1'b0) | (image_h_out_full_n == 1'b0) | (ddr_buffer_out_out_full_n == 1'b0) | (invert_X_out_full_n == 1'b0) | (image_w_out_full_n == 1'b0) | (1'b0 == DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        image_w_out_write = 1'b1;
    end else begin
        image_w_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (invert_Y_out_full_n == 1'b0) | (image_h_out_full_n == 1'b0) | (ddr_buffer_out_out_full_n == 1'b0) | (invert_X_out_full_n == 1'b0) | (image_w_out_full_n == 1'b0) | (1'b0 == DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        invert_X_out_blk_n = invert_X_out_full_n;
    end else begin
        invert_X_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (invert_Y_out_full_n == 1'b0) | (image_h_out_full_n == 1'b0) | (ddr_buffer_out_out_full_n == 1'b0) | (invert_X_out_full_n == 1'b0) | (image_w_out_full_n == 1'b0) | (1'b0 == DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        invert_X_out_write = 1'b1;
    end else begin
        invert_X_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        invert_Y_out_blk_n = invert_Y_out_full_n;
    end else begin
        invert_Y_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (invert_Y_out_full_n == 1'b0) | (image_h_out_full_n == 1'b0) | (ddr_buffer_out_out_full_n == 1'b0) | (invert_X_out_full_n == 1'b0) | (image_w_out_full_n == 1'b0) | (1'b0 == DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_full_n) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        invert_Y_out_write = 1'b1;
    end else begin
        invert_Y_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_din = DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (invert_Y_out_full_n == 1'b0) | (image_h_out_full_n == 1'b0) | (ddr_buffer_out_out_full_n == 1'b0) | (invert_X_out_full_n == 1'b0) | (image_w_out_full_n == 1'b0) | (1'b0 == DataMover_s2mm_32bits_hls_stream_hls_axis_ap_uint_8_1ul_0ul_0ul_0_ap_uint_32_volatile_int_int_ap_uint_1_ap_uint_1_i_0_out_full_n) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign ddr_buffer_out_out_din = ddr_buffer_out;

assign image_h_out_din = image_h;

assign image_w_out_din = image_w;

assign invert_X_out_din = invert_X;

assign invert_Y_out_din = invert_Y;

assign start_out = real_start;

endmodule //DataMoverUnit_s2mm_32bits_dataflow_in_loop_S2M_entry4
