-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity VideoMixerUnit is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    video_stream_in_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    video_stream_in_TVALID : IN STD_LOGIC;
    video_stream_in_TREADY : OUT STD_LOGIC;
    video_stream_in_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    video_stream_in_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    video_stream_in_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    video_stream_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    overlay_stream_in_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    overlay_stream_in_TVALID : IN STD_LOGIC;
    overlay_stream_in_TREADY : OUT STD_LOGIC;
    overlay_stream_in_TKEEP : IN STD_LOGIC_VECTOR (0 downto 0);
    overlay_stream_in_TSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
    overlay_stream_in_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    overlay_stream_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    video_stream_out_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    video_stream_out_TVALID : OUT STD_LOGIC;
    video_stream_out_TREADY : IN STD_LOGIC;
    video_stream_out_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
    video_stream_out_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
    video_stream_out_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    video_stream_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    image_h : IN STD_LOGIC_VECTOR (11 downto 0);
    image_w : IN STD_LOGIC_VECTOR (11 downto 0) );
end;


architecture behav of VideoMixerUnit is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "VideoMixerUnit_VideoMixerUnit,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.628000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=82,HLS_SYN_LUT=420,HLS_VERSION=2020_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_VideoMixer_fu_70_ap_start : STD_LOGIC;
    signal grp_VideoMixer_fu_70_ap_done : STD_LOGIC;
    signal grp_VideoMixer_fu_70_ap_idle : STD_LOGIC;
    signal grp_VideoMixer_fu_70_ap_ready : STD_LOGIC;
    signal grp_VideoMixer_fu_70_video_stream_in_TREADY : STD_LOGIC;
    signal grp_VideoMixer_fu_70_overlay_stream_in_TREADY : STD_LOGIC;
    signal grp_VideoMixer_fu_70_video_stream_out_TDATA : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_VideoMixer_fu_70_video_stream_out_TVALID : STD_LOGIC;
    signal grp_VideoMixer_fu_70_video_stream_out_TREADY : STD_LOGIC;
    signal grp_VideoMixer_fu_70_video_stream_out_TKEEP : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_VideoMixer_fu_70_video_stream_out_TSTRB : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_VideoMixer_fu_70_video_stream_out_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_VideoMixer_fu_70_video_stream_out_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_VideoMixer_fu_70_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal regslice_both_video_stream_out_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_video_stream_in_V_data_V_U_apdone_blk : STD_LOGIC;
    signal video_stream_in_TDATA_int_regslice : STD_LOGIC_VECTOR (23 downto 0);
    signal video_stream_in_TVALID_int_regslice : STD_LOGIC;
    signal video_stream_in_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_video_stream_in_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_video_stream_in_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal video_stream_in_TKEEP_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_video_stream_in_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_video_stream_in_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_video_stream_in_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal video_stream_in_TSTRB_int_regslice : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_video_stream_in_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_video_stream_in_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_video_stream_in_V_user_V_U_apdone_blk : STD_LOGIC;
    signal video_stream_in_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_video_stream_in_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_video_stream_in_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_video_stream_in_V_last_V_U_apdone_blk : STD_LOGIC;
    signal video_stream_in_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_video_stream_in_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_video_stream_in_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_overlay_stream_in_V_data_V_U_apdone_blk : STD_LOGIC;
    signal overlay_stream_in_TDATA_int_regslice : STD_LOGIC_VECTOR (7 downto 0);
    signal overlay_stream_in_TVALID_int_regslice : STD_LOGIC;
    signal overlay_stream_in_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_overlay_stream_in_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_overlay_stream_in_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal overlay_stream_in_TKEEP_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_overlay_stream_in_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_overlay_stream_in_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_overlay_stream_in_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal overlay_stream_in_TSTRB_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_overlay_stream_in_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_overlay_stream_in_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_overlay_stream_in_V_user_V_U_apdone_blk : STD_LOGIC;
    signal overlay_stream_in_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_overlay_stream_in_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_overlay_stream_in_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_overlay_stream_in_V_last_V_U_apdone_blk : STD_LOGIC;
    signal overlay_stream_in_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_overlay_stream_in_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_overlay_stream_in_V_last_V_U_ack_in : STD_LOGIC;
    signal video_stream_out_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_video_stream_out_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_video_stream_out_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_video_stream_out_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_video_stream_out_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_video_stream_out_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_video_stream_out_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_video_stream_out_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_video_stream_out_V_user_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_video_stream_out_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_video_stream_out_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_video_stream_out_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_video_stream_out_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_video_stream_out_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component VideoMixerUnit_VideoMixer IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        video_stream_in_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
        video_stream_in_TVALID : IN STD_LOGIC;
        video_stream_in_TREADY : OUT STD_LOGIC;
        video_stream_in_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
        video_stream_in_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
        video_stream_in_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        video_stream_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        overlay_stream_in_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        overlay_stream_in_TVALID : IN STD_LOGIC;
        overlay_stream_in_TREADY : OUT STD_LOGIC;
        overlay_stream_in_TKEEP : IN STD_LOGIC_VECTOR (0 downto 0);
        overlay_stream_in_TSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
        overlay_stream_in_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        overlay_stream_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        video_stream_out_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
        video_stream_out_TVALID : OUT STD_LOGIC;
        video_stream_out_TREADY : IN STD_LOGIC;
        video_stream_out_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
        video_stream_out_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
        video_stream_out_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        video_stream_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        image_h : IN STD_LOGIC_VECTOR (11 downto 0);
        image_w : IN STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component VideoMixerUnit_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_VideoMixer_fu_70 : component VideoMixerUnit_VideoMixer
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_VideoMixer_fu_70_ap_start,
        ap_done => grp_VideoMixer_fu_70_ap_done,
        ap_idle => grp_VideoMixer_fu_70_ap_idle,
        ap_ready => grp_VideoMixer_fu_70_ap_ready,
        video_stream_in_TDATA => video_stream_in_TDATA_int_regslice,
        video_stream_in_TVALID => video_stream_in_TVALID_int_regslice,
        video_stream_in_TREADY => grp_VideoMixer_fu_70_video_stream_in_TREADY,
        video_stream_in_TKEEP => video_stream_in_TKEEP_int_regslice,
        video_stream_in_TSTRB => video_stream_in_TSTRB_int_regslice,
        video_stream_in_TUSER => video_stream_in_TUSER_int_regslice,
        video_stream_in_TLAST => video_stream_in_TLAST_int_regslice,
        overlay_stream_in_TDATA => overlay_stream_in_TDATA_int_regslice,
        overlay_stream_in_TVALID => overlay_stream_in_TVALID_int_regslice,
        overlay_stream_in_TREADY => grp_VideoMixer_fu_70_overlay_stream_in_TREADY,
        overlay_stream_in_TKEEP => overlay_stream_in_TKEEP_int_regslice,
        overlay_stream_in_TSTRB => overlay_stream_in_TSTRB_int_regslice,
        overlay_stream_in_TUSER => overlay_stream_in_TUSER_int_regslice,
        overlay_stream_in_TLAST => overlay_stream_in_TLAST_int_regslice,
        video_stream_out_TDATA => grp_VideoMixer_fu_70_video_stream_out_TDATA,
        video_stream_out_TVALID => grp_VideoMixer_fu_70_video_stream_out_TVALID,
        video_stream_out_TREADY => grp_VideoMixer_fu_70_video_stream_out_TREADY,
        video_stream_out_TKEEP => grp_VideoMixer_fu_70_video_stream_out_TKEEP,
        video_stream_out_TSTRB => grp_VideoMixer_fu_70_video_stream_out_TSTRB,
        video_stream_out_TUSER => grp_VideoMixer_fu_70_video_stream_out_TUSER,
        video_stream_out_TLAST => grp_VideoMixer_fu_70_video_stream_out_TLAST,
        image_h => image_h,
        image_w => image_w);

    regslice_both_video_stream_in_V_data_V_U : component VideoMixerUnit_regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => video_stream_in_TDATA,
        vld_in => video_stream_in_TVALID,
        ack_in => regslice_both_video_stream_in_V_data_V_U_ack_in,
        data_out => video_stream_in_TDATA_int_regslice,
        vld_out => video_stream_in_TVALID_int_regslice,
        ack_out => video_stream_in_TREADY_int_regslice,
        apdone_blk => regslice_both_video_stream_in_V_data_V_U_apdone_blk);

    regslice_both_video_stream_in_V_keep_V_U : component VideoMixerUnit_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => video_stream_in_TKEEP,
        vld_in => video_stream_in_TVALID,
        ack_in => regslice_both_video_stream_in_V_keep_V_U_ack_in,
        data_out => video_stream_in_TKEEP_int_regslice,
        vld_out => regslice_both_video_stream_in_V_keep_V_U_vld_out,
        ack_out => video_stream_in_TREADY_int_regslice,
        apdone_blk => regslice_both_video_stream_in_V_keep_V_U_apdone_blk);

    regslice_both_video_stream_in_V_strb_V_U : component VideoMixerUnit_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => video_stream_in_TSTRB,
        vld_in => video_stream_in_TVALID,
        ack_in => regslice_both_video_stream_in_V_strb_V_U_ack_in,
        data_out => video_stream_in_TSTRB_int_regslice,
        vld_out => regslice_both_video_stream_in_V_strb_V_U_vld_out,
        ack_out => video_stream_in_TREADY_int_regslice,
        apdone_blk => regslice_both_video_stream_in_V_strb_V_U_apdone_blk);

    regslice_both_video_stream_in_V_user_V_U : component VideoMixerUnit_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => video_stream_in_TUSER,
        vld_in => video_stream_in_TVALID,
        ack_in => regslice_both_video_stream_in_V_user_V_U_ack_in,
        data_out => video_stream_in_TUSER_int_regslice,
        vld_out => regslice_both_video_stream_in_V_user_V_U_vld_out,
        ack_out => video_stream_in_TREADY_int_regslice,
        apdone_blk => regslice_both_video_stream_in_V_user_V_U_apdone_blk);

    regslice_both_video_stream_in_V_last_V_U : component VideoMixerUnit_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => video_stream_in_TLAST,
        vld_in => video_stream_in_TVALID,
        ack_in => regslice_both_video_stream_in_V_last_V_U_ack_in,
        data_out => video_stream_in_TLAST_int_regslice,
        vld_out => regslice_both_video_stream_in_V_last_V_U_vld_out,
        ack_out => video_stream_in_TREADY_int_regslice,
        apdone_blk => regslice_both_video_stream_in_V_last_V_U_apdone_blk);

    regslice_both_overlay_stream_in_V_data_V_U : component VideoMixerUnit_regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => overlay_stream_in_TDATA,
        vld_in => overlay_stream_in_TVALID,
        ack_in => regslice_both_overlay_stream_in_V_data_V_U_ack_in,
        data_out => overlay_stream_in_TDATA_int_regslice,
        vld_out => overlay_stream_in_TVALID_int_regslice,
        ack_out => overlay_stream_in_TREADY_int_regslice,
        apdone_blk => regslice_both_overlay_stream_in_V_data_V_U_apdone_blk);

    regslice_both_overlay_stream_in_V_keep_V_U : component VideoMixerUnit_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => overlay_stream_in_TKEEP,
        vld_in => overlay_stream_in_TVALID,
        ack_in => regslice_both_overlay_stream_in_V_keep_V_U_ack_in,
        data_out => overlay_stream_in_TKEEP_int_regslice,
        vld_out => regslice_both_overlay_stream_in_V_keep_V_U_vld_out,
        ack_out => overlay_stream_in_TREADY_int_regslice,
        apdone_blk => regslice_both_overlay_stream_in_V_keep_V_U_apdone_blk);

    regslice_both_overlay_stream_in_V_strb_V_U : component VideoMixerUnit_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => overlay_stream_in_TSTRB,
        vld_in => overlay_stream_in_TVALID,
        ack_in => regslice_both_overlay_stream_in_V_strb_V_U_ack_in,
        data_out => overlay_stream_in_TSTRB_int_regslice,
        vld_out => regslice_both_overlay_stream_in_V_strb_V_U_vld_out,
        ack_out => overlay_stream_in_TREADY_int_regslice,
        apdone_blk => regslice_both_overlay_stream_in_V_strb_V_U_apdone_blk);

    regslice_both_overlay_stream_in_V_user_V_U : component VideoMixerUnit_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => overlay_stream_in_TUSER,
        vld_in => overlay_stream_in_TVALID,
        ack_in => regslice_both_overlay_stream_in_V_user_V_U_ack_in,
        data_out => overlay_stream_in_TUSER_int_regslice,
        vld_out => regslice_both_overlay_stream_in_V_user_V_U_vld_out,
        ack_out => overlay_stream_in_TREADY_int_regslice,
        apdone_blk => regslice_both_overlay_stream_in_V_user_V_U_apdone_blk);

    regslice_both_overlay_stream_in_V_last_V_U : component VideoMixerUnit_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => overlay_stream_in_TLAST,
        vld_in => overlay_stream_in_TVALID,
        ack_in => regslice_both_overlay_stream_in_V_last_V_U_ack_in,
        data_out => overlay_stream_in_TLAST_int_regslice,
        vld_out => regslice_both_overlay_stream_in_V_last_V_U_vld_out,
        ack_out => overlay_stream_in_TREADY_int_regslice,
        apdone_blk => regslice_both_overlay_stream_in_V_last_V_U_apdone_blk);

    regslice_both_video_stream_out_V_data_V_U : component VideoMixerUnit_regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_VideoMixer_fu_70_video_stream_out_TDATA,
        vld_in => grp_VideoMixer_fu_70_video_stream_out_TVALID,
        ack_in => video_stream_out_TREADY_int_regslice,
        data_out => video_stream_out_TDATA,
        vld_out => regslice_both_video_stream_out_V_data_V_U_vld_out,
        ack_out => video_stream_out_TREADY,
        apdone_blk => regslice_both_video_stream_out_V_data_V_U_apdone_blk);

    regslice_both_video_stream_out_V_keep_V_U : component VideoMixerUnit_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_VideoMixer_fu_70_video_stream_out_TKEEP,
        vld_in => grp_VideoMixer_fu_70_video_stream_out_TVALID,
        ack_in => regslice_both_video_stream_out_V_keep_V_U_ack_in_dummy,
        data_out => video_stream_out_TKEEP,
        vld_out => regslice_both_video_stream_out_V_keep_V_U_vld_out,
        ack_out => video_stream_out_TREADY,
        apdone_blk => regslice_both_video_stream_out_V_keep_V_U_apdone_blk);

    regslice_both_video_stream_out_V_strb_V_U : component VideoMixerUnit_regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_VideoMixer_fu_70_video_stream_out_TSTRB,
        vld_in => grp_VideoMixer_fu_70_video_stream_out_TVALID,
        ack_in => regslice_both_video_stream_out_V_strb_V_U_ack_in_dummy,
        data_out => video_stream_out_TSTRB,
        vld_out => regslice_both_video_stream_out_V_strb_V_U_vld_out,
        ack_out => video_stream_out_TREADY,
        apdone_blk => regslice_both_video_stream_out_V_strb_V_U_apdone_blk);

    regslice_both_video_stream_out_V_user_V_U : component VideoMixerUnit_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_VideoMixer_fu_70_video_stream_out_TUSER,
        vld_in => grp_VideoMixer_fu_70_video_stream_out_TVALID,
        ack_in => regslice_both_video_stream_out_V_user_V_U_ack_in_dummy,
        data_out => video_stream_out_TUSER,
        vld_out => regslice_both_video_stream_out_V_user_V_U_vld_out,
        ack_out => video_stream_out_TREADY,
        apdone_blk => regslice_both_video_stream_out_V_user_V_U_apdone_blk);

    regslice_both_video_stream_out_V_last_V_U : component VideoMixerUnit_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => grp_VideoMixer_fu_70_video_stream_out_TLAST,
        vld_in => grp_VideoMixer_fu_70_video_stream_out_TVALID,
        ack_in => regslice_both_video_stream_out_V_last_V_U_ack_in_dummy,
        data_out => video_stream_out_TLAST,
        vld_out => regslice_both_video_stream_out_V_last_V_U_vld_out,
        ack_out => video_stream_out_TREADY,
        apdone_blk => regslice_both_video_stream_out_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_VideoMixer_fu_70_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_VideoMixer_fu_70_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_VideoMixer_fu_70_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_VideoMixer_fu_70_ap_ready = ap_const_logic_1)) then 
                    grp_VideoMixer_fu_70_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_VideoMixer_fu_70_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state4, regslice_both_video_stream_out_V_data_V_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_VideoMixer_fu_70_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (regslice_both_video_stream_out_V_data_V_U_apdone_blk = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_done_assign_proc : process(ap_CS_fsm_state4, regslice_both_video_stream_out_V_data_V_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (regslice_both_video_stream_out_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state4, regslice_both_video_stream_out_V_data_V_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (regslice_both_video_stream_out_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_VideoMixer_fu_70_ap_start <= grp_VideoMixer_fu_70_ap_start_reg;
    grp_VideoMixer_fu_70_video_stream_out_TREADY <= (video_stream_out_TREADY_int_regslice and ap_CS_fsm_state3);
    overlay_stream_in_TREADY <= regslice_both_overlay_stream_in_V_data_V_U_ack_in;

    overlay_stream_in_TREADY_int_regslice_assign_proc : process(grp_VideoMixer_fu_70_overlay_stream_in_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            overlay_stream_in_TREADY_int_regslice <= grp_VideoMixer_fu_70_overlay_stream_in_TREADY;
        else 
            overlay_stream_in_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    video_stream_in_TREADY <= regslice_both_video_stream_in_V_data_V_U_ack_in;

    video_stream_in_TREADY_int_regslice_assign_proc : process(grp_VideoMixer_fu_70_video_stream_in_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            video_stream_in_TREADY_int_regslice <= grp_VideoMixer_fu_70_video_stream_in_TREADY;
        else 
            video_stream_in_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    video_stream_out_TVALID <= regslice_both_video_stream_out_V_data_V_U_vld_out;
end behav;
